### ISSUE TITLE
NEW FEATURE: Add Virtual Media resource and datasource

### ISSUE THREAD

**Issue by mikeletux** [dell/terraform-provider-redfish#13]
This issue is to keep track of the implementation of VirtualMedia resource and datasource.
- **Resource**: The user must be able to mount and unmount ISOs place on HTTP, CIFS or NFS shares.
- **Datasource**: The user must be able to check the different virtual medias that can be used in the resource.

- [x] VirtualMedia resource implementation.
- [x] VirtualMedia datasource implementation.

**Comment by grantcurell** [comment]
@mikeletux can this one be closed?

**Comment by mikeletux** [comment]
@grantcurell yes we can 😄
