### ISSUE TITLE
NEW FEATURE: Add resource for manager reset

### ISSUE THREAD

**Issue by anupamaloke** [dell/terraform-provider-redfish#16]
### Description

Add a new Redfish provider resource for manager reset. It should support all the reset type operations that is supported by a BMC for e.g. GracefulRestart, ForceRestart etc.

### New or Affected Resource(s)

New resource

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by grantcurell** [comment]
@anupamaloke / @mikeletux is this different then #15 ? Is this for the idrac itself that we're talking about?

**Comment by mikeletux** [comment]
@grantcurell This is for Manager reset (idrac) I would say.
@anupamaloke can you provide more details?

**Comment by anupamaloke** [comment]
@grantcurell, @mikeletux, you are right. This is the iDRAC reset :-)

**Comment by gokul-srivathsan** [comment]
Manager reset has been implemented.
