### ISSUE TITLE
Wait for BIOS update job to finish

### ISSUE THREAD

**Issue by brutus333** [dell/terraform-provider-redfish#18]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
While updating BIOS setup using this provider I noticed that it created a job on the iDRAC but it did not wait for the job to finish.
IMHO the correct behavior (from TF perspective) it is to wait (sync or async) for the resource configuration to be applied.
The code can be changed to use existing method `WaitForJobToFinish`
### New or Affected Resource(s)

* redfish_bios

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file.
resource "redfish_bios" "bios" {

  redfish_server {
    endpoint = "https://192.168.8.103:6443"
    ssl_insecure = true
  }
  attributes = {
    "SysProfile" = "PerfOptimized"
  }
  settings_apply_time = "OnReset"
  action_after_apply = "ForceRestart"
  wait_to_finish = true
}

```

### References

* #0000

**Comment by grantcurell** [comment]
@mikeletux I can take this one. I'll add a common function for waiting for a job to complete. We'll need this for a lot of different tasks.

**Comment by brutus333** [comment]
@grantcurell : maybe a good way to deal with this is by using StateChangeConf method from terraform sdk resource package. I'm trying to test a code change based on this method - I'll come back with results.

**Comment by mikeletux** [comment]
@grantcurell there is a function already to wait for a job to be completed. check *common/job_management.go*.

We need to discuss whether the functions on that file needs to be moved to redfish/common.go to have all of them in the same place.

Also let's sync up with @anupamaloke this Thursday to see how we can move forward with this 😄

**Comment by brutus333** [comment]
I tested StateChangeConf and I have now a functional provider version which waits for the job to complete before going further. I'll issue a PR.

**Comment by mikeletux** [comment]
thanks @brutus333 !!!
