### ISSUE TITLE
Should getSystemResource() be in some sort of common file?

### ISSUE THREAD

**Issue by grantcurell** [dell/terraform-provider-redfish#21]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm working on #15. In [resource_redfish_bios.go](https://github.com/dell/terraform-provider-redfish/blob/2dfe7a52ce39334d2e506d628ec27b56c159eeb7/redfish/resource_redfish_bios.go#L345) I see that there is a function getSystemResource which resolves an instance of GoFish's service to a concrete system which I figure will be reused across multiple modules. I tried [asking on StackOverflow](https://stackoverflow.com/questions/66484247/where-is-the-correct-place-to-handle-common-functions-in-a-terraform-provider) to see if there is a good way to handle functionality shared across different resources. It would seem Go doesn't have stylistic guidance on the subject.

Right now my code is referencing getSystemResource in `resource_redfish_bios.go` which I figure is undesirable. Is there a preferred way to handle this scenario?

**Comment by anupamaloke** [comment]
@grantcurell, I agree with you that it is best to move the ```getSystemResource``` to a common file rather than importing it from the bios resource.  IMHO, I guess the best way to handle it would be to create a new internal ```computersystem.go``` and move the ```getSystemResource``` to this file. Let me know what do you think.

**Comment by grantcurell** [comment]
> @grantcurell, I agree with you that it is best to move the `getSystemResource` to a common file rather than importing it from the bios resource. IMHO, I guess the best way to handle it would be to create a new internal `computersystem.go` and move the `getSystemResource` to this file. Let me know what do you think.

That seems reasonable to me - though admittedly my opinion is still weak since I have so little experience in Go. I can include that as part of https://github.com/dell/terraform-provider-redfish/pull/22 though
