### ISSUE TITLE
NEW FEATURE: resource_user_account acceptance tests

### ISSUE THREAD

**Issue by mikeletux** [dell/terraform-provider-redfish#33]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
New acceptance tests for resource_user_account

### New or Affected Resource(s)

* resource_user_account

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file.
```

**Comment by gokul-srivathsan** [comment]
Please refer https://github.com/dell/terraform-provider-redfish/blob/main/redfish/resource_redfish_user_account_test.go

**Comment by mikeletux** [comment]
I'm glad you guys keep developing this. I was so lucky to start this project with @anupamaloke @sunilvijendra @grantcurell and @RickDavis404 . Kudos to them as well. Great memories :smile: 
You can close this issue btw :rocket:

**Comment by anupamaloke** [comment]
Thank you @mikeletux :-)

**Comment by gokul-srivathsan** [comment]
user account resource acceptance test has been completed.
