### ISSUE TITLE
NEW FEATURE: GitHub actions to create binaries when versions are tagged

### ISSUE THREAD

**Issue by mikeletux** [dell/terraform-provider-redfish#45]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As soon as new versions of this provider are tagged, we need to kick off a pipeline that eventually compile the provider (for windows, linux and darwing) and publish it within the packages section.

Also this is a requirement for publishing provider binaries to the terraform registry:
https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-

### Tasks
- [ ] Copy the GoReleaser configuration from the [terraform-provider-scaffolding](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.goreleaser.yml) repository to the root of your repository. 
- [ ] Copy the GitHub Actions workflow from the [terraform-provider-scaffolding](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml) repository to .github/workflows/release.yml in your repository. 

These actions above are only the ones regarding this repo. To fully integrate with the terraform registry, all of them must be followed:
https://www.terraform.io/docs/registry/providers/publishing.html#github-actions-preferred-

**Comment by gokul-srivathsan** [comment]
We are doing this and we are creating the binaries (Refer: https://github.com/dell/terraform-provider-redfish/releases/tag/v1.0.0)
