### ISSUE TITLE
Github actions for publishing provider on Terraform registry

### ISSUE THREAD

**Issue by mikeletux** [dell/terraform-provider-redfish#46]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In order to publish this provider to Terraform registry, some requisites need to be met according this: [Publishing Providers](https://www.terraform.io/docs/registry/providers/publishing.html).  

Task list:
  - [ ] Create and export a signing key that you plan on using to sign your provider releases. See [Preparing and Adding a Signing Key](https://www.terraform.io/docs/registry/providers/publishing.html#preparing-and-adding-a-signing-key) for more information
  - [ ] Copy the [GoReleaser configuration from the terraform-provider-scaffolding repository](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.goreleaser.yml) to the root of your repository.
  - [ ] Copy the [GitHub Actions workflow from the terraform-provider-scaffolding repository](https://github.com/hashicorp/terraform-provider-scaffolding/blob/main/.github/workflows/release.yml) to *.github/workflows/release.yml* in your repository. 
  - [ ] Go to Settings > Secrets in your repository, and add the following secrets:
  -- [GPG_PRIVATE_KEY](https://www.terraform.io/docs/registry/providers/publishing.html#gpg_private_key) - Your ASCII-armored GPG private key. You can export this with *gpg --armor --export-secret-keys [key ID or email]*. 
 -- [PASSPHRASE](https://www.terraform.io/docs/registry/providers/publishing.html#passphrase) - The passphrase for your GPG private key. 
  - [ ] Push a new valid version tag (e.g. *v1.2.3*) to test that the GitHub Actions releaser is working.

**Comment by jmpolom** [comment]
What is the status of this? Is help needed? It appears there is a [fork](https://registry.terraform.io/providers/lexfrei/redfish/latest) that has been published to the tf registry. Are there any active maintainers for this project at Dell?

**Comment by gokul-srivathsan** [comment]
We are actively maintaining this provider https://registry.terraform.io/providers/dell/redfish/latest. We won't be using github actions for publishing as we have our own pipeline for publishing.
