### ISSUE TITLE
NEW FEATURE: Implement SimpleUpdate on the provider

### ISSUE THREAD

**Issue by mikeletux** [dell/terraform-provider-redfish#7]
- [ ] - Write CRUD Operations that carries out the expected behavior ( Update the firmware of the machine)
- [ ] - Create unit tests for the code written

**Comment by sunilvijendra** [comment]
@mikeletux,
As a first step, I have started working on creating data source for the Firmware Inventory

**Comment by mikeletux** [comment]
Hey @sunilvijendra ,

Yeah, let's do that. It'll be great to retrieve all firmware versions from all components just to figure out the initial state from the server.

From my experience... how do you think you'll be doing that? The firmware/software inventory has information about installed versions but it is kind of weird for me, because you find packages with "installed" word and also with "current". Kind of confusing.

I was working some time back to implement the resource itself. Actually as per today, Gofish library doesn't implement a method that allows to get/post/path... with custom headers. I'm about to submit a pull request to solve that to Sean and his library.

We could sync up on our meeting on Thursdays to see how we can build this together.

Let me know!

**Comment by sunilvijendra** [comment]
Hey @mikeletux ,
Yes, the prefix confused me too initially! "Installed" is the prefix we can filter on to get the  installed Firmware and version details. 

With gofish@0.9, the UpdateService has a method to fetch Firmware Inventory. We can use the same. 

Let me know about the meeting and we can discuss further.
